[workspace]
members = [
    "grpc",
    "grpc-protobuf",
    "grpc-examples/greeter",
    "grpc-examples/route_guide",
    "grpc-compiler",
    "long-tests/with-rust",
    "interop",
    "protoc-rust-grpc",
    "ci-gen",
]
