[package]

name = "grpc"
version = "0.8.3"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Rust implementation of gRPC"
repository = "https://github.com/stepancheg/grpc-rust"
readme = "../README.md"
keywords = ["grpc"]
edition = "2018"

[dependencies]
log             = "0.4"
log-ndc         = "0.2.*"
futures         = "0.3.1"
tokio           = { version = "~0.2.6", features = ["net", "uds", "io-util", "time"] }
httpbis         = "~0.9"
tls-api         = "0.4.*"
tls-api-stub    = "0.4.*"
bytes           = "0.5.*"
base64          = "0.9"

[dev-dependencies]
log-ndc-env-logger = "~0.2"

[lib]
doctest = false
